### ISSUE TITLE
Feature Request: let `generate_formatter` also support the keyword args from `format`

### ISSUE THREAD

**Issue by schlichtanders** [JuliaLang/Formatting.jl#114]
I find the `format` function awesome. It is very intuitive. And sometimes, I even like to put it into a kind of generate_formatter, like `myformat(x) = format(x, width=3)`.

This is slow as said in the README. Hence it would be awesome if `generate_formatter(width=3, ...)` would work to create an efficient version of this.

**Comment by kescobo** [comment]
This package is no longer maintained, see #111

Check out Format.jl as an alternative, which is actively maintained and close to a drop in replacement.
