### ISSUE TITLE
Move to JuliaLang

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/Formatting.jl#9]
@lindahua, since this package has garnered some interest and solves a general class of problems in Julia, and since you seem quite busy these days, how about moving this package to JuliaLang?  Assuming, of course, it's wanted there.

Cc: @StefanKarpinski

**Comment by ScottPJones** [comment]
:+1:

**Comment by lindahua** [comment]
If the core team thinks it deserves a spot in JuliaLang, I have no problem with the moving.

**Comment by StefanKarpinski** [comment]
Seems like a good idea to me as well.

**Comment by ScottPJones** [comment]
Can't say what the core team thinks, but I'd say it more than deserves a spot in JuliaLang, at least part should probably be moved into Base... @tbreloff and I have been discussing additions, and there seems to be a lot of interest on the google groups... this is common enabling functionality.

**Comment by tbreloff** [comment]
JuliaLang I can kinda see, but not Base. I think we should keep base as tiny as possible. Either way, we should flesh out the functionality that the community wants before pressing to move it beyond a forked package.

**Comment by StefanKarpinski** [comment]
Agreed – moving to JuliaLang just lets more people hack on it more easily and gives it more visibility.

**Comment by ScottPJones** [comment]
@tbreloff Base is so huge as it is... and there is even totally unused stuff that could be moved out to make room for something that a lot of people have been asking for... but yes, the functionality needs to be completely fleshed out before that should ever happen.

**Comment by tbreloff** [comment]
Stefan: I clearly can't help in moving this to JuliaLang, but I'd be willing to "hack on it" extensively. Your guidance as to exactly how to approach this would be helpful as you're much more in tune with the needs of the community. (could this be a good project at the hackathon tomorrow?)

**Comment by ScottPJones** [comment]
I'll look forward to meeting you tomorrow... A lot of interesting stuff to think about during the hackathon (formatting, strings, database access...)!

**Comment by lindahua** [comment]
I need temporary admin rights to make the move.

**Comment by StefanKarpinski** [comment]
Done. Go for it.

**Comment by lindahua** [comment]
Done
